package dev.getelements.elements.crossfire.model;

import dev.getelements.elements.sdk.annotation.ElementPublic;

@ElementPublic
public interface ProtocolMessage {

    /**
     * Returns the type of the message.
     *
     * @return the type
     */
    ProtocolMessageType getType();

    /**
     * Indicates if the message is server-only. Server-only signals are generated by the server and not sent by clients.
     * A client attempting to send a server-only signal will receive an error.
     *
     * @return true if the signal is server-only, false otherwise
     */
    default boolean isServerOnly() {
        return false;
    }

}
