
# A docker-compose file which incorporates just the third-party services required
# to make SocialEngine run.  This does not actually make containers for actual
# social engine services.  This exposes ports so that the local machine may access
# the local instances.

version: '3'
services:

  mongo:
    image: mongo:6.0.9
    command:
      - mongod
      - --replSet
      - local-test
    deploy:
      replicas: 1
    networks:
      - elements
    ports:
      - "27017:27017"

  rs-init:
    build:
      context: rs-init
    deploy:
      replicas: 1
    networks:
      - elements

networks:
  elements:
