name: Publish Snapshot to Sonatype

on:
  push:
    tags: ["v*"]
    branches: [ main ]

jobs:

  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Cloning the Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven Credentials
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Build and Publish Snapshot
        run: mvn -B -Pcentral-publish clean deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
