name: Publish Snapshot to Sonatype

on:
  push:
    branches: [ main ]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Configure Maven settings for Sonatype Central
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: |
            [
              {
                "id": "central",
                "username": "${{ secrets.SONATYPE_USERNAME }}",
                "password": "${{ secrets.SONATYPE_PASSWORD }}"
              }
            ]

      - name: Import GPG private key (manual, from base64)
        shell: bash
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "pinentry-mode loopback" > ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent || true
          echo "$SIGNING_KEY" | base64 --decode > /tmp/private.key.asc
          gpg --batch --yes --import /tmp/private.key.asc
          gpg -K || true

      - name: Verify version is a SNAPSHOT
        id: ver
        run: |
          VER=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "version=$VER" >> $GITHUB_OUTPUT
          if [[ "$VER" != *-SNAPSHOT ]]; then
            echo "Current version is '$VER' which is not a SNAPSHOT. Skipping deploy."
            exit 0
          fi

      - name: Build and publish snapshot
        if: endsWith(steps.ver.outputs.version, '-SNAPSHOT')
        run: mvn --settings settings.xml -B clean deploy
