name: Publish Snapshot to Sonatype

on:
  push:
    branches: [ main ]

jobs:

  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - name: Cloning the Repository
        uses: actions/checkout@v4

      - name: Get current version
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current project version: $VERSION"

      - name: Ensure Snapshot Version
        id: next_version
        run: |

          CURRENT=${{ steps.version.outputs.version }}
      
          # Exit if NOT a snapshot
          if [[ "$CURRENT" != *-SNAPSHOT ]]; then
            echo "::error::Expected a -SNAPSHOT version, but found '$CURRENT'."
            echo "The main branch must end with -SNAPSHOT before running a release."
            echo "Please bump the version in pom.xml and push before retrying."
            exit 1
          fi

      - name: Set up JDK 21 and Maven Credentials
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Build and Publish Snapshot
        run: mvn -B -Pcentral-publish clean deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
